channels:
- conda-forge
dependencies:
- MonkeyType
- autoflake
- black
- blackdoc
- custom-inherit
- flake8
- flake8-docstrings
- ipykernel
- ipython
- isort
- mypy
- nbsphinx
- numba
- numpy
- pip
- pre-commit
- pyls-black
- pyls-isort
- pyls-mypy
- pytest
- pytest-cov
- pytest-mypy
- pytest-xdist
- python=3.8
- setuptools-scm
- sphinx
- sphinx_rtd_theme
- sphinxcontrib-spelling
- tox-conda
- typing-extensions
- xarray
- pip:
  - flake8-mypy
  - mypy-extensions
  - pyenchant
  - pytest-accept
  - pytest-monkeytype
name: cmomy-env
