---
channels:
    - conda-forge
dependencies:
    - custom-inherit
    - ipykernel
    - ipython
    - numba
    - numpy
    - pip
    - pytest
    - pytest-cov
    - pytest-xdist
    - python=3.10
    - setuptools-scm
    - typing-extensions
    - xarray
    - pip:
          - pytest-accept
name: cmomy-env
