package: 
  name: cmomy
  version: '0.1'

source: 
  git_rev: v0.1
  git_url: https://github.com/wpk-nist-gov/cmomy.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - cmomy

about:
  home: https://github.com/wpk-nist-gov/cmomy
  license: 
  license_file: 
